import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import { Toaster } from 'react-hot-toast'
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ProductedProviders from "@/components/providers/SessionProvider";
import { getServerSession } from "next-auth";
import { GET } from '@/app/api/auth/[...nextauth]/route';
import ReduxProvider from "@/components/providers/ReduxProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Scita Web Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(GET);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductedProviders session={session}>
          <ReduxProvider>
            <ReactQueryProvider>
              <ThemeProvider attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange >
                {children}
                <Toaster position="bottom-right" />
              </ThemeProvider>
            </ReactQueryProvider>
          </ReduxProvider>
        </ProductedProviders>
      </body>
    </html >
  );
}
